---

- name: install
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - xorg
    - xorg-server
    - xorg-xinit
    - xorg-apps
    - xterm
    - ttf-dejavu
    - ttf-liberation
    - noto-fonts